###
GET http://localhost:8080/other/query?param=test

###
GET http://localhost:8080/other/header
myHeader: header-value

###
POST http://localhost:8080/other/body
Content-Type: text/plain

Hello world!
